### ISSUE TITLE
add tox

### ISSUE THREAD

**Issue by rpappalax** [Kinto/kinto-integration-tests#26]

**Comment by stephendonner** [comment]
This was added in https://github.com/Kinto/kinto-integration-tests/commit/ddf4dca2761d08aaa590374ed555d002d798934c and https://github.com/Kinto/kinto-integration-tests/commit/6534499c93c11ad0c4e7c011cdcfdc1f799b7f41, but isn't currently working, at least not from the Dockerfile: https://github.com/Kinto/kinto-integration-tests/issues/36

**Comment by stephendonner** [comment]
This is working, now[0]; if you concur, @rpappalax, mind closing it out?

[0] https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/kinto.integration.stage/27/console
