### ISSUE TITLE
/bin/sh: tox: not found error when running Dockerfile via Jenkins, due to Tox not being installed in the container

### ISSUE THREAD

**Issue by stephendonner** [Kinto/kinto-integration-tests#36]
Current Jenkins jobs[0] running against the ```stage``` environment are failing in the ```tox``` build-pipeline step, as follows:

```
[Pipeline] {
[Pipeline] sh
[kinto.stage@2] Running shell script
+ chmod +x run
[Pipeline] sh
[kinto.stage@2] Running shell script
+ ./run
/bin/sh: tox: not found
```
Full console output here, for easier reference: https://gist.github.com/stephendonner/7d77f83fc2340284a5c6be22bc7d249c

@chartjes looked into this today, and got this partially working; filed this to track.

[0] https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/kinto.stage/3/consoleText

**Comment by stephendonner** [comment]
With https://github.com/Kinto/kinto-integration-tests/pull/38 merged, this is still an issue.  @chartjes , once https://github.com/Kinto/kinto-integration-tests/pull/39 is in, would you mind taking another look at this?  This'll help unblock us from proving that the ops-pipeline workflow works; thanks!

**Comment by chartjes** [comment]
@stephendonner - I just pushed the change to the Dockerfile and rebuilt the Docker image. Should be okay now

**Comment by stephendonner** [comment]
Fixed by https://github.com/Kinto/kinto-integration-tests/commit/a8171f6b31f74354244feacfb81221e8b658be07 and https://github.com/Kinto/kinto-integration-tests/pull/40
