### ISSUE TITLE
Add fxtestbot webhook for GitHub-repo events (PRs, pushes, Issues?)

### ISSUE THREAD

**Issue by stephendonner** [Kinto/kinto-integration-tests#49]
@chartjes - as discussed in IRC

We could greatly benefit from seeing GitHub PRs, merges (and potentially Issues) events.

Click on Settings at the top of the repo
Webhooks
Add webhook
For Payload URL, put https://fxtestbot.herokuapp.com/hubot/gh-repo-events
Content type is "application/json"
Choose "Let me select individual events" - for Web projects, we typically have: 1) Issues 2)Push 3) Pull request checked
Select/leave the "Active" checkbox checked, and add the webhook

I'm not sure if we need to do anything on the fxtestbot side - @davehunt would know for sure.

**Comment by chartjes** [comment]
@stephendonner Implemented, closing for now

**Comment by stephendonner** [comment]
Yay, I've just tested that at least the PR portion works; looking forward to the rest of it!

<img width="1792" alt="screen shot 2017-11-29 at 11 33 56 pm" src="https://user-images.githubusercontent.com/387249/33419122-dfb992a8-d55d-11e7-8f36-2a3d4936b318.png">
