### ISSUE TITLE
Enable kinto-integration-tests repo in Travis CI

### ISSUE THREAD

**Issue by stephendonner** [Kinto/kinto-integration-tests#56]
Now that https://github.com/Kinto/kinto-integration-tests/pull/53 is in, we should (probably) go ahead and enable this repo on Travis CI.

@chartjes mind doing the honors?

**Comment by davehunt** [comment]
I just noticed that flake8 is failing. We should enable Travis CI for this repository to prevent these issues (or at least catch them early). /cc @chartjes

**Comment by chartjes** [comment]
I believe I've added it in

https://travis-ci.org/Kinto/kinto-integration-tests

**Comment by davehunt** [comment]
Looks like it's working: https://travis-ci.org/Kinto/kinto-integration-tests/builds/329601977. I'd say we can close this, even though that build isn't complete (apparently there's a long Travis CI backlog currently).

**Comment by stephendonner** [comment]
Yep; closing since this is auto-triggered, now, via commits/PRs.
